site_name: Sibernetic Config Gen Developer Docs
theme: readthedocs
pages:
- [index.md, Home]
- [Usage_Options/usage_options.md, Usage Options, Usage Options]
- [Config_File_Sections/positions.md, Config File Sections, Positions]
- [Config_File_Sections/velocities.md, Config File Sections, Velocities]
- [Config_File_Sections/connections.md, Config File Sections, Connections]
- [Config_File_Sections/membranes.md, Config File Sections, Membranes]
- [Config_File_Sections/particle_mem_index.md, Config File Sections, ParticleMemIndex]
- [Minimal_Object_Reqs/minimal_object_reqs.md, Minimal Object Reqs, Minimal Object Reqs]
- [Creating_New_Scenes/creating_new_scenes.md, Creating New Scenes, Creating New Scenes]
