site_name: Sibernetic Config Gen Developer Docs
theme: readthedocs
pages:
- [index.md, Home]
- [Config_File_Sections/connections.md, Config File Sections, Connections]
- [Config_File_Sections/positions.md, Config File Sections, Positions]
- [Config_File_Sections/velocities.md, Config File Sections, Velocities]
